#!/usr/bin/env bash

goos_arr=(
    "darwin"
    "linux"
)
goarch_arr=(
    "386"
    "amd64"
)

cd /go/src/olsu || exit

go get

for os in "${goos_arr[@]}"; do
    for arch in "${goarch_arr[@]}"; do
        GOOS="$os" GOARCH="$arch" go build -v -o "olsu-${os}-${arch}"
    done
done
