#!/usr/bin/env bash

set -e

docker run --rm --log-driver none \
    -v "${PWD}/olsu":/go/src/olsu \
    -v "${PWD}/olsu_build":/bin/olsu_build \
    -w /bin \
    golang:1.7.0 \
    bash -c "chmod +x olsu_build && ./olsu_build"

output_files=(
    "olsu-darwin-386.zip"
    "olsu-darwin-amd64.zip"
    "olsu-linux-386.zip"
    "olsu-linux-amd64.zip"
)

for file in "${output_files[@]}"; do
    zip -j "${file}" "olsu/${file%.zip}"
    rm "olsu/${file%.zip}"
done

GOARCH="amd64"
GOOS="darwin"

olsu="olsu-${GOOS}-${GOARCH}"

unzip "${olsu}.zip"

export OLSU_REPOSITORY=olsu
export OLSU_OWNER=Telling
export OLSU_DELETE_RELEASE=yes

./"$olsu" "Olsu v0.1.0" "v0.1.0" "Initial release of olsu." "${output_files[@]}"

rm "${output_files[@]}"
rm "$olsu"
